// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaXlJf96y7E_vdZa-vAUHJmRWddjGTOH4',
    appId: '1:320185282068:web:bfd4aaabb8e342da31c101',
    messagingSenderId: '320185282068',
    projectId: 'messagingapp-f2b01',
    authDomain: 'messagingapp-f2b01.firebaseapp.com',
    databaseURL: 'https://messagingapp-f2b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messagingapp-f2b01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_WAjKYDp2XwU5_Pa6E50tDE2yVzBIbC0',
    appId: '1:320185282068:android:14cd092c8c1b330331c101',
    messagingSenderId: '320185282068',
    projectId: 'messagingapp-f2b01',
    databaseURL: 'https://messagingapp-f2b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messagingapp-f2b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzZrerMmzUhOeYdJWRAIEoMwO_CdJKJw0',
    appId: '1:320185282068:ios:a8881790f73f0ad831c101',
    messagingSenderId: '320185282068',
    projectId: 'messagingapp-f2b01',
    databaseURL: 'https://messagingapp-f2b01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'messagingapp-f2b01.appspot.com',
    iosBundleId: 'com.example.messagingapp',
  );
}
